NIUKE_CAMPUS_SEEDS = (
    {
        "company_name": "阿里巴巴",
        "group_name": "互联网大厂",
        "industry": "互联网/电商/云计算",
        "scale_text": "大型企业",
        "city_text": "全国/杭州",
        "official_site_url": "https://www.alibabagroup.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。优先作为企业专题与后续官网投递入口补链的起点，不直接作为 jobs 主表来源。",
    },
    {
        "company_name": "腾讯",
        "group_name": "互联网大厂",
        "industry": "互联网/社交/游戏",
        "scale_text": "大型企业",
        "city_text": "全国/深圳",
        "official_site_url": "https://www.tencent.com/zh-cn",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。优先服务校招批次、企业页和官网入口补齐。",
    },
    {
        "company_name": "字节跳动",
        "group_name": "互联网大厂",
        "industry": "互联网/内容平台/AI",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://www.bytedance.com/zh/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。后续可继续补实习、提前批与官方投递链接。",
    },
    {
        "company_name": "美团",
        "group_name": "互联网大厂",
        "industry": "互联网/本地生活/零售科技",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://about.meituan.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为本地生活与平台类校招专题企业入口。",
    },
    {
        "company_name": "京东",
        "group_name": "电商与供应链平台",
        "industry": "电商/零售/供应链",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://www.jd.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为电商与供应链方向企业专题入口。",
    },
    {
        "company_name": "百度",
        "group_name": "互联网大厂",
        "industry": "互联网/搜索/AI",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://www.baidu.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为搜索与 AI 企业专题入口。",
    },
    {
        "company_name": "华为",
        "group_name": "通信与硬件",
        "industry": "通信/硬件/终端",
        "scale_text": "大型企业",
        "city_text": "全国/深圳",
        "official_site_url": "https://www.huawei.com/cn/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为通信硬件类校招专题起点。",
    },
    {
        "company_name": "小米",
        "group_name": "通信与硬件",
        "industry": "消费电子/硬件/互联网",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://www.mi.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为消费电子与硬件企业专题入口。",
    },
    {
        "company_name": "快手",
        "group_name": "内容与平台",
        "industry": "互联网/短视频/直播",
        "scale_text": "大型企业",
        "city_text": "全国/北京",
        "official_site_url": "https://www.kuaishou.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为内容平台类校招专题入口。",
    },
    {
        "company_name": "网易",
        "group_name": "互联网大厂",
        "industry": "互联网/游戏/教育",
        "scale_text": "大型企业",
        "city_text": "全国/杭州",
        "official_site_url": "https://www.163.com/",
        "career_site_url": "",
        "description_text": "牛客校招专题种子目录。适合作为游戏与综合互联网企业专题入口。",
    },
)