from typing import Any


SOURCE_CATALOG: dict[str, dict[str, Any]] = {
    "boss": {
        "source_code": "boss",
        "source_name": "Boss直聘",
        "platform_code": "boss",
        "platform_name": "Boss直聘",
        "status": "beta",
        "enabled": True,
        "strategy": "requests_api",
        "description": "接口实验链路；当前常受环境校验影响，适合做 requests 探测与诊断，不建议作为主抓取方案。",
    },
    "boss_dp": {
        "source_code": "boss_dp",
        "source_name": "Boss直聘（浏览器拦截）",
        "platform_code": "boss",
        "platform_name": "Boss直聘",
        "status": "active",
        "enabled": True,
        "strategy": "browser_intercept",
        "description": "当前 Boss 主抓取方案；通过 DrissionPage 监听接口响应，整体比 requests 链路更贴近真实浏览器环境。",
    },
    "lagou": {
        "source_code": "lagou",
        "source_name": "拉勾",
        "platform_code": "lagou",
        "platform_name": "拉勾",
        "status": "beta",
        "enabled": True,
        "strategy": "browser_manual_intercept",
        "description": "浏览器打开搜索页；若命中滑动验证需人工通过。当前首屏优先读取 __NEXT_DATA__ 注水职位列表，后续分页主要依赖结果页 DOM 回退；近期 bundle 逆向显示站点更偏向路由切页 + 注水刷新，packet 分支暂未观察到稳定可依赖入口。",
    },
    "liepin": {
        "source_code": "liepin",
        "source_name": "猎聘",
        "platform_code": "liepin",
        "platform_name": "猎聘",
        "status": "active",
        "enabled": True,
        "strategy": "browser_intercept_api",
        "description": "通过浏览器拦截 pc-search-job 列表接口；热门城市优先走站内精确检索，更多城市会通过城市招聘网入口动态解析后再精确搜索。",
    },
    "job51": {
        "source_code": "job51",
        "source_name": "前程无忧",
        "platform_code": "51job",
        "platform_name": "前程无忧",
        "status": "active",
        "enabled": True,
        "strategy": "browser_intercept_api",
        "description": "通过浏览器拦截 search-pc 列表接口，并动态解析 51job 城市字典。",
    },
    "guopin": {
        "source_code": "guopin",
        "source_name": "国聘",
        "platform_code": "guopin",
        "platform_name": "国聘",
        "status": "active",
        "enabled": True,
        "strategy": "requests_api",
        "description": "直接请求 gp-api 的 jobs/v1/recom-job 与 jobs/v1/info；城市条件通过 search.district 精确传入，详情页链接拼接为 /job/detail?id=...。",
    },
    "jobmohrss": {
        "source_code": "jobmohrss",
        "source_name": "中国公共招聘网",
        "platform_code": "mohrss",
        "platform_name": "中国公共招聘网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "直接请求 /cjobs/jobinfolist/listJobinfolist 服务端分页页面，并解析隐藏字段 findjoblist 与 showgw 详情页，适合补公共就业体系和官方岗位来源。",
    },
    "healthr": {
        "source_code": "healthr",
        "source_name": "医药英才网",
        "platform_code": "healthr",
        "platform_name": "医药英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取医药英才网公开搜索页与职位详情页，适合补医疗卫生、医药销售、药企与医械岗位来源。",
    },
    "healthr_doctor": {
        "source_code": "healthr_doctor",
        "source_name": "医药英才网-医疗卫生",
        "platform_code": "healthr",
        "platform_name": "医药英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取医药英才网医疗卫生分类页与职位详情页，适合补医生、护士、医师等医疗卫生子垂直岗位来源。",
    },
    "buildhr": {
        "source_code": "buildhr",
        "source_name": "建筑英才网",
        "platform_code": "buildhr",
        "platform_name": "建筑英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取建筑英才网公开搜索页与职位详情页，适合补建筑设计、工程项目、施工与造价类岗位来源。",
    },
    "chenhr": {
        "source_code": "chenhr",
        "source_name": "化工英才网",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取化工英才网公开搜索页与职位详情页，适合补研发、工艺、生产管理和化工销售类岗位来源。",
    },
    "jxhg_chenhr": {
        "source_code": "jxhg_chenhr",
        "source_name": "化工英才网-精细化工",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取精细化工英才网子站公开搜索页与职位详情页，适合补精细化工、日化、新材料研发与生产岗位来源。",
    },
    "mhg_chenhr": {
        "source_code": "mhg_chenhr",
        "source_name": "化工英才网-煤化工",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取煤化工英才网子站公开搜索页与职位详情页，适合补煤化工、焦化、煤制油与煤制气岗位来源。",
    },
    "sysh_chenhr": {
        "source_code": "sysh_chenhr",
        "source_name": "化工英才网-石油化工",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取石油化工英才网子站公开搜索页与职位详情页，适合补石油炼制、石化工程与油气储运岗位来源。",
    },
    "newenergy_chenhr": {
        "source_code": "newenergy_chenhr",
        "source_name": "化工英才网-新能源",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取新能源英才网子站公开搜索页与职位详情页，适合补光伏、锂电、风能、储能与新能源材料岗位来源。",
    },
    "sales_chenhr": {
        "source_code": "sales_chenhr",
        "source_name": "化工英才网-销售英才",
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取化工销售英才网子站公开搜索页与职位详情页，适合补化工、医药、能源行业销售与市场岗位来源。",
    },
    "doctor_healthr": {
        "source_code": "doctor_healthr",
        "source_name": "医药英才网-医生",
        "platform_code": "healthr",
        "platform_name": "医药英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取医生子站公开搜索页与职位详情页，适合补临床医生、主任医师、主治医师等细分医疗岗位来源。",
    },
    "pha_healthr": {
        "source_code": "pha_healthr",
        "source_name": "医药英才网-药房药店",
        "platform_code": "healthr",
        "platform_name": "医药英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取药房子站公开搜索页与职位详情页，适合补执业药师、药店店员、药房管理与药品零售岗位来源。",
    },
    "env_buildhr": {
        "source_code": "env_buildhr",
        "source_name": "建筑英才网-环境环保",
        "platform_code": "buildhr",
        "platform_name": "建筑英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取环境/环保英才网子站公开搜索页与职位详情页，适合补环评、环境检测、环保工程与生态修复岗位来源。",
    },
    "construct_buildhr": {
        "source_code": "construct_buildhr",
        "source_name": "建筑英才网-建筑施工",
        "platform_code": "buildhr",
        "platform_name": "建筑英才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取建筑施工英才网子站公开搜索页与职位详情页，适合补施工管理、工程监理、安全与质量岗位来源。",
    },
    "ncss24365": {
        "source_code": "ncss24365",
        "source_name": "24365 国家大学生就业服务平台",
        "platform_code": "ncss",
        "platform_name": "24365 国家大学生就业服务平台",
        "status": "active",
        "enabled": True,
        "strategy": "requests_api",
        "description": "直接请求 /student/jobs/jobslist/ajax/ 列表接口，并补抓 /student/jobs/{job_id}/detail.html 详情页，适合补官方校招与高校来源职位。",
    },
    "qingdao_rc": {
        "source_code": "qingdao_rc",
        "source_name": "青岛人才招聘e站",
        "platform_code": "qingdao_rc",
        "platform_name": "青岛人才招聘e站",
        "status": "active",
        "enabled": True,
        "strategy": "requests_api",
        "description": "直接请求 qdzhrcww 的 jzQuery/findQuery 列表接口，并补抓 toDetail/toFwDetail 详情页，适合补青岛本地官方岗位来源。",
    },
    "qdhr": {
        "source_code": "qdhr",
        "source_name": "青帆引才",
        "platform_code": "qdhr",
        "platform_name": "青帆引才",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取 qdhr 的公开职位列表页和详情页，适合补青岛本地市场化岗位来源。",
    },
    "qlrc": {
        "source_code": "qlrc",
        "source_name": "齐鲁人才网",
        "platform_code": "qilu_rc",
        "platform_name": "齐鲁人才网",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取齐鲁人才网公开职位搜索页与详情页，适合补山东本地市场化综合岗位来源。",
    },
    "sdgxbys": {
        "source_code": "sdgxbys",
        "source_name": "山东高校毕业生就业市场主职位",
        "platform_code": "sdgxbys",
        "platform_name": "山东高校毕业生就业市场",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取山东高校毕业生就业市场主职位分页；列表内容通过页面内嵌压缩 payload 解码后解析，适合补省级公开职位主表来源。",
    },
    "sdgxbys_campus": {
        "source_code": "sdgxbys_campus",
        "source_name": "山东高校毕业生就业市场校园公告",
        "platform_code": "sdgxbys",
        "platform_name": "山东高校毕业生就业市场",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取山东高校毕业生就业市场公开 campus 公告分页与详情标题元信息，适合补省级校园招聘公告来源。",
    },
    "rcsd_talents": {
        "source_code": "rcsd_talents",
        "source_name": "人才山东引才公告",
        "platform_code": "rcsd",
        "platform_name": "人才山东",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取人才山东 demand/talents 静态分页栏目与公告详情，适合补山东省级引才与招聘公告来源。",
    },
    "shixiseng": {
        "source_code": "shixiseng",
        "source_name": "实习僧",
        "platform_code": "shixiseng",
        "platform_name": "实习僧",
        "status": "active",
        "enabled": True,
        "strategy": "browser_nuxt_detail",
        "description": "通过浏览器读取 Nuxt 注水数据，优先覆盖实习/校招岗位。",
    },
    "zhilian": {
        "source_code": "zhilian",
        "source_name": "智联招聘",
        "platform_code": "zhilian",
        "platform_name": "智联招聘",
        "status": "active",
        "enabled": True,
        "strategy": "browser_intercept_api",
        "description": "通过浏览器首屏注水加翻页接口拦截，优先读取 search/positions 真列表响应。",
    },
    "niuke_campus": {
        "source_code": "niuke_campus",
        "source_name": "牛客校招专题",
        "platform_code": "nowcoder",
        "platform_name": "牛客",
        "status": "active",
        "enabled": True,
        "strategy": "topic_directory",
        "description": "专题型来源；抓取牛客校招日程 API + 首页公开招聘动态，优先覆盖互联网/科技大厂校招批次与官网投递入口。",
    },
    "yingjiesheng": {
        "source_code": "yingjiesheng",
        "source_name": "应届生求职网专题",
        "platform_code": "yingjiesheng",
        "platform_name": "应届生求职网",
        "status": "active",
        "enabled": True,
        "strategy": "topic_directory",
        "description": "专题型来源；抓取应届生首页企业专题 + deadline 截止日期页，优先覆盖校招与名企专题入口。",
    },
    "dxy_job": {
        "source_code": "dxy_job",
        "source_name": "丁香人才专题",
        "platform_code": "dxy_job",
        "platform_name": "丁香人才",
        "status": "active",
        "enabled": True,
        "strategy": "topic_directory",
        "description": "专题型来源；抓取丁香人才首页单位目录 + 校招页 + 双选会参展单位 + 招聘公告详情，覆盖医疗医药行业。",
    },
    "wuba": {
        "source_code": "wuba",
        "source_name": "58同城招聘",
        "platform_code": "wuba",
        "platform_name": "58同城",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取 58同城 城市招聘搜索页与详情页，优先覆盖蓝领、本地服务、零售、物流、餐饮岗位；请求频率保守避免反爬。",
    },
    "jobonline": {
        "source_code": "jobonline",
        "source_name": "就业在线",
        "platform_code": "jobonline",
        "platform_name": "就业在线",
        "status": "beta",
        "enabled": True,
        "strategy": "topic_directory",
        "description": "人社部官方聚合平台；需通过阿里云 CSB + AES 加密对接，当地人社部门审批授权后方可获取 AppKey/Secret。当前仅做平台目录与外链映射，不直接作为大规模 jobs 主表来源。",
    },
    "gaoxiaojob": {
        "source_code": "gaoxiaojob",
        "source_name": "高校人才网",
        "platform_code": "gaoxiaojob",
        "platform_name": "高校人才网（高才网）",
        "status": "active",
        "enabled": True,
        "strategy": "requests_html",
        "description": "抓取高才网（gaoxiaojob.com）高校教师、科研、政府与事业单位、中小学、医学、企业招聘栏目；通过 JSON API 获取列表 HTML 并解析结构化字段。",
    },
    "unknown": {
        "source_code": "unknown",
        "source_name": "未知来源",
        "platform_code": "unknown",
        "platform_name": "未知来源",
        "status": "unknown",
        "enabled": False,
        "strategy": "unknown",
        "description": "未知来源。",
    },
}

SOURCE_LABELS = {code: item["source_name"] for code, item in SOURCE_CATALOG.items()}
SOURCE_LABELS["manual_seed"] = "专题种子"


def get_source_name(source_code: str) -> str:
    normalized = (source_code or "").strip().lower()
    if not normalized:
        normalized = "unknown"
    return SOURCE_LABELS.get(normalized, normalized)


def get_source_info(source_code: str) -> dict[str, Any]:
    normalized = (source_code or "").strip().lower()
    if not normalized:
        normalized = "unknown"
    return dict(SOURCE_CATALOG.get(normalized, SOURCE_CATALOG["unknown"]))


def list_source_catalog(*, include_disabled: bool = True) -> list[dict[str, Any]]:
    items = [dict(item) for code, item in SOURCE_CATALOG.items() if code != "unknown"]
    if not include_disabled:
        items = [item for item in items if item.get("enabled")]
    return sorted(items, key=lambda item: (not item.get("enabled", False), item.get("platform_name", ""), item.get("source_name", "")))
