from __future__ import annotations

from typing import Any


PLATFORM_CATALOG: list[dict[str, Any]] = [
    {
        "platform_code": "boss",
        "platform_name": "Boss直聘",
        "platform_category": "national-general",
        "platform_type": "商业招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["社招", "互联网", "销售", "运营"],
        "reliability_level": "medium",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["boss", "boss_dp"],
        "official_site_url": "https://www.zhipin.com/",
        "notes": "当前主抓取方案为 boss_dp 浏览器拦截；requests 链路仅保留为接口实验与诊断。",
    },
    {
        "platform_code": "zhilian",
        "platform_name": "智联招聘",
        "platform_category": "national-general",
        "platform_type": "商业招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["校招", "制造业", "传统行业", "白领"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["zhilian"],
        "official_site_url": "https://www.zhaopin.com/",
        "notes": "当前已实现首屏注水加 search/positions 半接口化分页。",
    },
    {
        "platform_code": "job51",
        "platform_name": "前程无忧",
        "platform_category": "national-general",
        "platform_type": "商业招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["名企", "文职", "技术岗", "传统企业"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["job51"],
        "official_site_url": "https://www.51job.com/",
        "notes": "当前为浏览器预热 Cookie 后的中浅分页 requests 化。",
    },
    {
        "platform_code": "liepin",
        "platform_name": "猎聘",
        "platform_category": "national-general",
        "platform_type": "商业招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["中高端", "管理岗", "3年+经验", "猎头渠道"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["liepin"],
        "official_site_url": "https://www.liepin.com/",
        "notes": "当前仍以浏览器辅助为主，requests 复放尚未稳定。",
    },
    {
        "platform_code": "lagou",
        "platform_name": "拉勾",
        "platform_category": "national-general",
        "platform_type": "商业招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["研发", "产品", "设计", "互联网"],
        "reliability_level": "medium",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["lagou"],
        "official_site_url": "https://www.lagou.com/",
        "notes": "当前接受浏览器辅助加人工验证检查点，不作为近期扩源模板。",
    },
    {
        "platform_code": "shixiseng",
        "platform_name": "实习僧",
        "platform_category": "vertical-campus",
        "platform_type": "垂直校招平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["实习", "应届", "校招", "名企实习"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["shixiseng"],
        "official_site_url": "https://www.shixiseng.com/",
        "notes": "列表、详情、公司接口已打通，是当前最成熟的校招/实习源之一。",
    },
    {
        "platform_code": "guopin",
        "platform_name": "国聘",
        "platform_category": "national-official",
        "platform_type": "官方招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["央企", "国企", "事业单位", "大型民企"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["guopin"],
        "official_site_url": "https://www.iguopin.com/",
        "notes": "当前适合继续服务央国企板块与官方口径校验。",
    },
    {
        "platform_code": "ncss24365",
        "platform_name": "24365 国家大学生就业服务平台",
        "platform_category": "national-official",
        "platform_type": "官方招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["校招", "应届", "实习", "高校来源"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["ncss24365"],
        "official_site_url": "https://www.ncss.cn/",
        "notes": "已接入 jobs 主表，可继续扩企业专题与官方投递链接。",
    },
    {
        "platform_code": "jobmohrss",
        "platform_name": "中国公共招聘网",
        "platform_category": "national-official",
        "platform_type": "官方招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["公共就业", "基层岗位", "事业单位", "社招"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["jobmohrss"],
        "official_site_url": "https://job.mohrss.gov.cn/",
        "notes": "适合补公共就业体系和官方岗位目录。",
    },
    {
        "platform_code": "chenhr",
        "platform_name": "化工英才网",
        "platform_category": "vertical-industry",
        "platform_type": "化工行业垂直招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["研发", "工艺", "生产管理", "化工销售"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["chenhr"],
        "official_site_url": "https://www.chenhr.com/",
        "notes": "当前已按公开搜索页与职位详情页接入，可作为研发、工艺、生产与化工销售垂直岗位补量源。",
    },
    {
        "platform_code": "qingdao_rc",
        "platform_name": "青岛人才招聘e站",
        "platform_category": "local-official",
        "platform_type": "地方官方人才网",
        "coverage_scope": "青岛",
        "region_scope": "山东",
        "suitable_for": ["本地官方", "国企", "事业单位", "重点企业"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["qingdao_rc"],
        "official_site_url": "https://fw.rc.qingdao.gov.cn/zhaopin/",
        "notes": "当前是青岛本地官方主力源，适合继续做区县与关键词扩量。",
    },
    {
        "platform_code": "qdhr",
        "platform_name": "青帆引才",
        "platform_category": "local-market",
        "platform_type": "地方市场化平台",
        "coverage_scope": "青岛",
        "region_scope": "山东",
        "suitable_for": ["本地市场化", "技术岗", "综合岗", "中小企业"],
        "reliability_level": "medium",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["qdhr"],
        "official_site_url": "http://laoshan.qdhr.com/",
        "notes": "当前已从技术岗补量源扩展成青岛市场化综合岗位主力源。",
    },
    {
        "platform_code": "sdgxbys",
        "platform_name": "山东高校毕业生就业市场主职位",
        "platform_category": "local-official",
        "platform_type": "省级官方就业平台",
        "coverage_scope": "山东",
        "region_scope": "山东",
        "suitable_for": ["校招", "泛岗", "省级公开职位", "高校毕业生"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["sdgxbys"],
        "official_site_url": "https://job.sdgxbys.cn/job/index",
        "notes": "当前更适合作为山东全省泛岗补量源，而非纯技术岗来源。",
    },
    {
        "platform_code": "sdgxbys_campus",
        "platform_name": "山东高校毕业生就业市场校园公告",
        "platform_category": "local-official",
        "platform_type": "省级官方就业平台",
        "coverage_scope": "山东",
        "region_scope": "山东",
        "suitable_for": ["校园公告", "校招", "高校来源"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["sdgxbys_campus"],
        "official_site_url": "https://job.sdgxbys.cn/campus/index",
        "notes": "当前适合补校园招聘公告，不宜直接按深度职位源口径看待。",
    },
    {
        "platform_code": "rcsd_talents",
        "platform_name": "人才山东引才公告",
        "platform_category": "local-official",
        "platform_type": "省级官方人才平台",
        "coverage_scope": "山东",
        "region_scope": "山东",
        "suitable_for": ["引才公告", "招聘公告", "高校科研院所"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["rcsd_talents"],
        "official_site_url": "https://web.rcsd.cn/rcsd20/demand/talents/",
        "notes": "适合作为山东省级公告型补量源，优先围绕招聘与优青。",
    },
    {
        "platform_code": "jiuye_online",
        "platform_name": "就业在线",
        "platform_category": "national-official",
        "platform_type": "官方聚合入口",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["平台发现", "官方目录", "入口索引"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "official-directory-only",
        "source_codes": [],
        "official_site_url": "https://www.jobonline.cn/",
        "notes": "更适合作为官方来源索引器，不建议直接作为 jobs 主表大规模职位源。",
    },
    {
        "platform_code": "qilu_rc",
        "platform_name": "齐鲁人才网",
        "platform_category": "local-market",
        "platform_type": "省级市场化平台",
        "coverage_scope": "山东",
        "region_scope": "山东",
        "suitable_for": ["制造业", "消费品", "供应链", "山东本地企业"],
        "reliability_level": "medium",
        "crawl_priority": "high",
        "current_status": "covered",
        "source_codes": ["qlrc"],
        "official_site_url": "https://www.qlrc.com/",
        "notes": "当前已按 SSR 列表卡片加详情页解析接入，可作为山东本地市场化综合岗位补量源。",
    },
    {
        "platform_code": "healthr",
        "platform_name": "医药英才网",
        "platform_category": "vertical-industry",
        "platform_type": "医药医疗垂直招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["医疗卫生", "药企", "医械", "医药销售"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["healthr", "healthr_doctor"],
        "official_site_url": "https://www.healthr.com/",
        "notes": "当前已接入主站公开搜索页与医疗卫生分类子源，可作为医疗卫生与医药垂直岗位补量源。",
    },
    {
        "platform_code": "buildhr",
        "platform_name": "建筑英才网",
        "platform_category": "vertical-industry",
        "platform_type": "建筑工程垂直招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["建筑设计", "土木工程", "工程项目", "施工造价"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["buildhr"],
        "official_site_url": "https://www.buildhr.com/",
        "notes": "当前已按公开搜索页与职位详情页接入，可作为建筑设计、工程项目与施工造价垂直岗位补量源。",
    },
    {
        "platform_code": "qingdao_public_employment",
        "platform_name": "青岛公共就业网",
        "platform_category": "local-official",
        "platform_type": "地方公共就业网",
        "coverage_scope": "青岛",
        "region_scope": "山东",
        "suitable_for": ["公共就业", "高校毕业生", "基层岗位", "公益招聘"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "planned",
        "source_codes": [],
        "official_site_url": "",
        "notes": "仍值得优先补，但需要先确认当前可访问入口与稳定列表页。",
    },
    {
        "platform_code": "niuke_campus",
        "platform_name": "牛客校招专题",
        "platform_category": "enterprise-topic",
        "platform_type": "企业专题平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["校招", "企业专题", "官网入口", "投递批次"],
        "reliability_level": "high",
        "crawl_priority": "high",
        "current_status": "planned",
        "source_codes": ["niuke_campus"],
        "official_site_url": "https://www.nowcoder.com/",
        "notes": "更适合优先接专题目录和企业入口，而不是直接追全站职位。",
    },
    {
        "platform_code": "yingjiesheng",
        "platform_name": "应届生求职网",
        "platform_category": "enterprise-topic",
        "platform_type": "企业专题平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["校招", "宣讲会", "企业专题", "邮箱投递"],
        "reliability_level": "medium",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["yingjiesheng"],
        "official_site_url": "https://www.yingjiesheng.com/",
        "notes": "当前已接入首页企业专题导入，适合作为校招专题与投递入口补充，不直接进入 jobs 主表。",
    },
    {
        "platform_code": "same_city_58",
        "platform_name": "58同城 / 赶集直招",
        "platform_category": "blue-collar",
        "platform_type": "本地生活招聘平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["蓝领", "本地服务", "零售", "物流"],
        "reliability_level": "low",
        "crawl_priority": "medium",
        "current_status": "planned",
        "source_codes": [],
        "official_site_url": "https://www.58.com/",
        "notes": "岗位量大，但信息质量分层明显，后续应单独板块展示而非混入白领分析。",
    },
    {
        "platform_code": "yupao",
        "platform_name": "鱼泡网",
        "platform_category": "blue-collar",
        "platform_type": "蓝领垂直平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["建筑", "装修", "工地", "技工"],
        "reliability_level": "medium",
        "crawl_priority": "low",
        "current_status": "planned",
        "source_codes": [],
        "official_site_url": "https://www.yupao.com/",
        "notes": "如切蓝领板块，这类站点的价值会高于继续扩白领平台。",
    },
    {
        "platform_code": "dxy_job",
        "platform_name": "丁香人才",
        "platform_category": "vertical-industry",
        "platform_type": "行业垂直平台",
        "coverage_scope": "全国",
        "region_scope": "全国",
        "suitable_for": ["医疗", "医药", "医院岗位"],
        "reliability_level": "high",
        "crawl_priority": "medium",
        "current_status": "covered",
        "source_codes": ["dxy_job"],
        "official_site_url": "https://www.jobmd.cn/",
        "notes": "当前已接入首页公开单位目录、医院招聘计划、校招专题、campus 招聘公告、双选会活动、双选会参展单位与求职快讯导入，适合作为医疗行业专题与招聘入口补充，不直接进入 jobs 主表。",
    },
]


def _matches_filter(item: dict[str, Any], *, platform_category: str, current_status: str, crawl_priority: str, region_scope: str) -> bool:
    if platform_category and str(item.get("platform_category") or "") != platform_category:
        return False
    if current_status and str(item.get("current_status") or "") != current_status:
        return False
    if crawl_priority and str(item.get("crawl_priority") or "") != crawl_priority:
        return False
    if region_scope and str(item.get("region_scope") or "") != region_scope:
        return False
    return True


def list_platform_catalog(
    *,
    platform_category: str = "",
    current_status: str = "",
    crawl_priority: str = "",
    region_scope: str = "",
) -> list[dict[str, Any]]:
    normalized_category = str(platform_category or "").strip().lower()
    normalized_status = str(current_status or "").strip().lower()
    normalized_priority = str(crawl_priority or "").strip().lower()
    normalized_region = str(region_scope or "").strip()

    items = [
        dict(item)
        for item in PLATFORM_CATALOG
        if _matches_filter(
            item,
            platform_category=normalized_category,
            current_status=normalized_status,
            crawl_priority=normalized_priority,
            region_scope=normalized_region,
        )
    ]
    return sorted(items, key=lambda item: (str(item.get("current_status") or ""), str(item.get("crawl_priority") or ""), str(item.get("platform_name") or "")))


def get_platform_catalog_filters() -> dict[str, list[str]]:
    def unique_values(field_name: str) -> list[str]:
        values = {str(item.get(field_name) or "").strip() for item in PLATFORM_CATALOG if str(item.get(field_name) or "").strip()}
        return sorted(values)

    return {
        "platform_categories": unique_values("platform_category"),
        "current_statuses": unique_values("current_status"),
        "crawl_priorities": unique_values("crawl_priority"),
        "region_scopes": unique_values("region_scope"),
    }